In [45]:
import numpy as np

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[11,12,13], [14,15,16]])

arr = np.array([[1,2,3], [4,5,6]])


array([1, 2, 3])

In [46]:
arr[0]

array([1, 2, 3])

In [47]:
arr[0,]

array([1, 2, 3])

In [48]:
arr[1,1:]

array([5, 6])

In [49]:
arr[:, 0]

array([1, 4])

In [50]:
arr[:, 0][:, np.newaxis]

array([[1],
       [4]])

In [53]:
a = np.array([1,2,3,4,5,6])
b = np.array([True, False, True, True, False, False])
c = a[b]
c

array([1, 3, 4])

In [56]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,2,2,4])
arr1==arr2

array([False,  True, False,  True])

In [57]:
arr1>=arr2

array([False,  True,  True,  True])

In [58]:
np.all(arr1==arr2)

False

In [60]:
arr3 = np.array([1,2,3,4])
np.all(arr1==arr3)

True

In [61]:
sum(arr1>10)

0

In [62]:
sum(arr1<3)  

2

In [63]:
arr1<3

array([ True,  True, False, False])

In [64]:
np.logical_and(True, False)

False